name: Unity DocFx
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Move everything inside the manual/ folder
        run: |
          mkdir -p manual
          if [ -d Documentation~ ] && [ "$(ls -A Documentation~)" ]; then
            mv -v Documentation~/* manual/
          else
            mkdir -p Documentation~
          fi
          mv -v manual Documentation~/manual

      - name: Generate index page
        run: echo 'This page redirects to the [manual](manual/).' > Documentation~/index.md

      - name: Generate main Table of Contents
        run: |
          echo '- name: Manual
            href: manual/
            homepage: manual/index.md
          - name: Scripting API
            href: api/
            homepage: api/index.md' > Documentation~/toc.yml

      - name: Generate manual Table of Contents
        run: |
          if [ -f Documentation~/manual/TableOfContents.md ]; then
            mv Documentation~/manual/TableOfContents.md Documentation~/manual/toc.md
          fi
          if [ -f Documentation~/manual/toc.md ]; then
            sed -i -e 's/*/#/g' Documentation~/manual/toc.md
            sed -i -e 's/     /#/g' Documentation~/manu
