name: Generate and Commit DocFX JSON

on:
  push:
    branches:
      - main

jobs:
  generate-docfx-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate DocFX JSON
        run: |
          # Replace this with your script to generate docfx.json
          # Example:
          echo '{
            "metadata": {
              "appVersion": "1.0",
              "projectName": "My DocFX Project"
            },
            "build": {
              "content": ["*.md"],
              "dest": "_site"
            }
          }' > docfx.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docfx.json
          git commit -m "Generate docfx.json"
          git push

