name: Generate DocFX Documentation
inputs:
  github_token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: false
on:
  push:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true  # If you have submodules, set to 'true'

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version

    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.58/docfx.zip
        unzip docfx.zip -d ./docfx

    - name: Generate Documentation
      run: |
        chmod +x ./docfx/docfx.exe
        mono ./docfx/docfx.exe build docfx_project/docfx.json

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github_token }}
        publish_branch: gh-pages
        publish_dir: _site
