name: Generate DocFX Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.58/docfx.zip
        unzip docfx.zip -d ./docfx

    - name: Create docfx_project folder and docfx.json
      run: |
        mkdir -p docfx_project
        if [ ! -f docfx_project/docfx.json ]; then
          echo '{
            "metadata": [
              {
                "src": [
                  {
                    "files": [
                      "**/*.cs",
                      "**/*.md"
                    ],
                    "exclude": [
                      "**/obj/**",
                      "**/bin/**"
                    ],
                    "src": "./"
                  }
                ],
                "dest": "api"
              }
            ],
            "build": {
              "content": [
                {
                  "files": [
                    "**/*.md"
                  ],
                  "src": "./",
                  "dest": "_site/docs",
                  "exclude": [
                    "**/obj/**",
                    "**/bin/**"
                  ]
                },
                {
                  "files": [
                    "api/**.yml"
                  ],
                  "src": "./",
                  "dest": "_site/api",
                  "exclude": [
                    "**/obj/**",
                    "**/bin/**"
                  ]
                }
              ],
              "resource": [
                {
                  "files": [
                    "images/**"
                  ],
                  "src": "./",
                  "dest": "_site/images"
                }
              ],
              "globalMetadata": {
                "_appTitle": "Unity Logger Public Documentation"
              },
              "template": [
                "default"
              ],
              "dest": "_site"
            }
          }' > docfx_project/docfx.json
        fi

    - name: Generate Documentation
      run: |
        chmod +x ./docfx/docfx.exe
        mono ./docfx/docfx.exe build docfx_project/docfx.json

    - name: List DocFX output
      run: ls -R docfx_project/_site

    - name: List output directory
      run: ls docfx_project/_site

    - name: Echo contents of _site before deployment
      run: ls -R docfx_project/_site
      
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: docfx_project/_site
